services:
  timescale-db:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_DB: packet-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd
    ports:
      - "63000:5432" # 重複しないポート番号かつ排除されてもいいポート番号を指定
    volumes:
      - ./data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=30
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c work_mem=5MB
      -c min_wal_size=512MB
      -c max_wal_size=2GB
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c max_worker_processes=2
      -c max_parallel_workers_per_gather=1
      -c max_parallel_workers=2
      -c max_parallel_maintenance_workers=1
