services:
  timescale-db:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_DB: packet-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd
    ports:
      - "13432:5432" # 重複しないポート番号かつ排除されてもいいポート番号を指定
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'  # すべてのIPアドレスからの接続を許可